spring:
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13306/lubricant?serverTimezone=Asia/Seoul
    username: local
    password: local
  data:
    mongodb:
      uri: mongodb://localhost:27018
      database: lubricant
    redis:
      timeout: 3000ms
      connect-timeout: 3000ms
      cluster:
        nodes: localhost:8000
      lettuce:
        cluster:
          refresh:
            adaptive: true
            period: 60s
  jpa:
    open-in-view: false